---
deployment:
  tasks:
    - export DEPLOYPATH=/home/okremkk7s2ms/_wildcard_.suncitytechno.com/school-management/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    # - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
    # - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css